# Seldon configuration

## Source Sass/css to document:
source: ../sq2/sass/

## Destination for built docs
destination: ./

## Handlebars templates for documentation markup
templates:
   layout: templates/layout.hbs
   example: templates/example.hbs
